#! /bin/sh
# Dependency installation script for buildroots (server daemon start).
# Author: Abdullah Alabd (abdullah.alabd.else@gmail.com)


case "$1" in
start)
echo "Starting init script for Module Loading"
start-stop-daemon -S -n init -a /.ldd_modules_init_scripts/scull_load
start-stop-daemon -S -n init -a /.ldd_modules_init_scripts/module_load -- faulty
start-stop-daemon -S -n init -a /.ldd_modules_init_scripts/module_load -- hello
;;
stop)
echo "Removing user modules"
start-stop-daemon -K -n scull_load
start-stop-daemon -K -n module_load
start-stop-daemon -S -n init -a /.ldd_modules_init_scripts/scull_unload
start-stop-daemon -S -n init -a /.ldd_modules_init_scripts/module_unload -- faulty
start-stop-daemon -S -n init -a /.ldd_modules_init_scripts/module_unload -- hello
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0
